### ISSUE TITLE
The hero.jpg show a bug

### ISSUE THREAD

**Issue by leo2n** [jhu724/minimal-academic#2]
hello,
    I find a BUG in photo show, hero.jpg and portrait.jpg in same folder static/img, but portrait.jpg could show True, but hero.jpg show False, here is proof:
![image](https://user-images.githubusercontent.com/17608761/43752837-60d4b8d0-9a35-11e8-923e-eaee21a9e30d.png)

**Comment by leo2n** [comment]
Hello!
    I don't know why file name show messy code, could you help me to find the error location? Thank you

**Comment by jhu724** [comment]
Hi @leo2n, were you able to run the `exampleSite`? I'm not sure why your hero isn't working. The Hugo call is happening in the file `masthead_hero.html`, I would look in there and try to debug. 

Also, your screenshot suggests you didn't name your own hero image `hero.jpg`. Can you please make sure you've done that, or set the name to what you want in the appropriate markdown file (like `exampleSite/content/blog/first.md`).

**Comment by leo2n** [comment]
Hello!
    I had runned exampleSite, It shows the same result, but I found a question, 
![image](https://user-images.githubusercontent.com/17608761/43813135-eff9903c-9af6-11e8-8194-55ac8abbfa0a.png), avatar has it key-value, but portrait.jpg hasn't, I try add its key-value, but nothing happend.

**Comment by leo2n** [comment]
Hello!
    I just generated hugo public files, and I found in index.html, it show below:
![image](https://user-images.githubusercontent.com/17608761/43813299-ade417ac-9af7-11e8-8996-99fd005a5261.png)
I don't know why, if you need more debug information, please tell me, I will provide any debug information you need, thank you!

**Comment by jhu724** [comment]
The `avatar` has a value in the `config.toml` because it is meant to be site-wide. The hero image is set per post. Look in `exampleSite/content/blog/first.md` and notice that the front-matter is: 
```
title: "This is a blog post"
hero_image: "hero.jpg"
date: 2018-07-24T17:44:36-07:00
description: "This is a blog description."
```

Try changing the value of `hero_image` here.

**Comment by leo2n** [comment]
Hello!
    The question is solved, thank you!

**Comment by leo2n** [comment]
Hello!
    Do you have a interest to create a new feature, TAGS, that can give some article a new tag name and people could through tags to find article, thank you!

**Comment by jhu724** [comment]
You're welcome!

Tags and taxonomies are definitely on my todo list. Feel free to open a PR as well!
